python train.py \
    --model_path /home/yuhonglan/Models/Llama-2-7b-chat-hf \
    --dataset_path /home/yuhonglan/llm/Finetune_LLaMA/data/zh-data01 \
    --lora_rank 8 \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 1 \
    --num_train_epochs 3 \
    --save_steps 1000 \
    --save_total_limit 2 \
    --learning_rate 2e-5 \
    --fp16 \
    --remove_unused_columns false \
    --logging_steps 50 \
    --output_dir /home/yuhonglan/llm/rpc_llm/finetune_model \
    --rank -1